
import { MenuItem, Order } from './types';

export const menuItems: MenuItem[] = [
  // Starters
  {
    id: 1,
    name: "Paneer Tikka",
    category: "starters",
    price: 299,
    imageUrl: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?q=80&w=400&h=300&auto=format",
    ingredients: ["Cottage cheese", "Yogurt", "Spices", "Bell peppers", "Onion"],
    dietaryTag: "veg",
    rating: 4.7,
    reviewCount: 52,
    description: "Soft chunks of paneer marinated in a spicy yogurt mixture and grilled to perfection with onions and bell peppers.",
    cookingTime: "20 min",
    spicyLevel: "medium",
    calories: 320,
    allergens: ["Dairy"]
  },
  {
    id: 2,
    name: "Samosa",
    category: "starters",
    price: 149,
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=400&h=300&auto=format",
    ingredients: ["Potatoes", "Peas", "Pastry dough", "Spices", "Herbs"],
    dietaryTag: "veg",
    rating: 4.5,
    reviewCount: 65,
    description: "Crispy pastry triangles filled with spiced potatoes and peas, deep-fried until golden and served with tangy tamarind chutney.",
    cookingTime: "30 min",
    spicyLevel: "medium",
    calories: 250,
    allergens: ["Gluten"]
  },
  {
    id: 3,
    name: "Chicken 65",
    category: "starters",
    price: 349,
    imageUrl: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?q=80&w=400&h=300&auto=format",
    ingredients: ["Chicken", "Yogurt", "Red chili", "Curry leaves", "Ginger-garlic paste"],
    dietaryTag: "non-veg",
    rating: 4.8,
    reviewCount: 76,
    description: "Spicy deep-fried chicken bites marinated with authentic South Indian spices, curry leaves, and red chilies.",
    cookingTime: "25 min",
    spicyLevel: "hot",
    calories: 380,
    allergens: ["Dairy"]
  },
  {
    id: 4,
    name: "Dahi Puri",
    category: "starters",
    price: 179,
    imageUrl: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?q=80&w=400&h=300&auto=format",
    ingredients: ["Puris", "Yogurt", "Tamarind chutney", "Mint chutney", "Potatoes", "Sev"],
    dietaryTag: "veg",
    rating: 4.6,
    reviewCount: 48,
    description: "Hollow crispy puris filled with potatoes, topped with yogurt, sweet and tangy chutneys, and crunchy sev.",
    cookingTime: "15 min",
    spicyLevel: "medium",
    calories: 210,
    allergens: ["Dairy", "Gluten"]
  },
  {
    id: 5,
    name: "Tandoori Prawns",
    category: "starters",
    price: 499,
    imageUrl: "https://images.unsplash.com/photo-1559742811-822873691df8?q=80&w=400&h=300&auto=format",
    ingredients: ["King prawns", "Yogurt", "Tandoori masala", "Lemon", "Ginger-garlic paste"],
    dietaryTag: "non-veg",
    rating: 4.9,
    reviewCount: 62,
    description: "Jumbo prawns marinated in yogurt and tandoori spices, grilled in a clay oven for a smoky flavor.",
    cookingTime: "20 min",
    spicyLevel: "medium",
    calories: 290,
    allergens: ["Shellfish", "Dairy"]
  },
  {
    id: 6,
    name: "Aloo Tikki",
    category: "starters",
    price: 159,
    imageUrl: "https://images.unsplash.com/photo-1475090169767-40ed8d18f67d?q=80&w=400&h=300&auto=format",
    ingredients: ["Potatoes", "Green peas", "Spices", "Breadcrumbs", "Coriander"],
    dietaryTag: "veg",
    rating: 4.4,
    reviewCount: 55,
    description: "Crispy potato patties stuffed with spiced green peas, shallow-fried and served with mint and tamarind chutneys.",
    cookingTime: "25 min",
    spicyLevel: "mild",
    calories: 230,
    allergens: ["Gluten"]
  },
  {
    id: 7,
    name: "Veg Spring Rolls",
    category: "starters",
    price: 199,
    imageUrl: "https://images.unsplash.com/photo-1623341214825-9f4f963727da?q=80&w=400&h=300&auto=format",
    ingredients: ["Rice paper", "Carrots", "Cabbage", "Bell peppers", "Bean sprouts"],
    dietaryTag: "vegan",
    rating: 4.3,
    reviewCount: 42,
    description: "Crispy rolls filled with julienned vegetables, deep-fried until golden and served with sweet chili sauce.",
    cookingTime: "20 min",
    spicyLevel: "mild",
    calories: 210,
    allergens: ["Gluten"]
  },
  {
    id: 8,
    name: "Papdi Chaat",
    category: "starters",
    price: 189,
    imageUrl: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=400&h=300&auto=format",
    ingredients: ["Papdis", "Yogurt", "Potatoes", "Chickpeas", "Chutneys", "Sev"],
    dietaryTag: "veg",
    rating: 4.5,
    reviewCount: 51,
    description: "Crispy flour crackers topped with potatoes, chickpeas, yogurt, and a blend of sweet, tangy, and spicy chutneys.",
    cookingTime: "15 min",
    spicyLevel: "medium",
    calories: 240,
    allergens: ["Dairy", "Gluten"]
  },
  {
    id: 9,
    name: "Onion Bhaji",
    category: "starters",
    price: 179,
    imageUrl: "https://images.unsplash.com/photo-1668236543090-82575a50cf2f?q=80&w=400&h=300&auto=format",
    ingredients: ["Onions", "Gram flour", "Spices", "Green chilies", "Herbs"],
    dietaryTag: "vegan",
    rating: 4.4,
    reviewCount: 47,
    description: "Crispy fritters made with sliced onions, chickpea flour, and spices, deep-fried until golden brown.",
    cookingTime: "20 min",
    spicyLevel: "medium",
    calories: 180,
    allergens: []
  },
  {
    id: 10,
    name: "Chilli Fish",
    category: "starters",
    price: 329,
    imageUrl: "https://images.unsplash.com/photo-1559847844-5315695dadae?q=80&w=400&h=300&auto=format",
    ingredients: ["Fish fillets", "Bell peppers", "Onions", "Garlic", "Soy sauce"],
    dietaryTag: "non-veg",
    rating: 4.7,
    reviewCount: 58,
    description: "Crispy batter-fried fish tossed in a spicy Indo-Chinese sauce with bell peppers and onions.",
    cookingTime: "25 min",
    spicyLevel: "hot",
    calories: 310,
    allergens: ["Fish", "Soy"]
  },
  
  // Main Course
  {
    id: 11,
    name: "Butter Chicken",
    category: "main",
    price: 399,
    imageUrl: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=400&h=300&auto=format",
    ingredients: ["Chicken", "Tomato", "Butter", "Cream", "Spices"],
    dietaryTag: "non-veg",
    rating: 4.9,
    reviewCount: 102,
    description: "Tender chicken cooked in a rich and creamy tomato-based sauce with butter and aromatic spices.",
    cookingTime: "40 min",
    spicyLevel: "medium",
    calories: 540,
    allergens: ["Dairy"]
  },
  {
    id: 12,
    name: "Paneer Butter Masala",
    category: "main",
    price: 349,
    imageUrl: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?q=80&w=400&h=300&auto=format",
    ingredients: ["Paneer", "Tomatoes", "Cream", "Butter", "Spices"],
    dietaryTag: "veg",
    rating: 4.8,
    reviewCount: 89,
    description: "Soft paneer cubes simmered in a rich, creamy tomato sauce with butter and traditional spices.",
    cookingTime: "35 min",
    spicyLevel: "medium",
    calories: 480,
    allergens: ["Dairy"]
  },
  {
    id: 13,
    name: "Dal Makhani",
    category: "main",
    price: 279,
    imageUrl: "https://images.unsplash.com/photo-1626200419199-391ae4a39873?q=80&w=400&h=300&auto=format",
    ingredients: ["Black lentils", "Kidney beans", "Butter", "Cream", "Spices"],
    dietaryTag: "veg",
    rating: 4.7,
    reviewCount: 78,
    description: "Creamy black lentils and kidney beans slow-cooked with butter, cream, and aromatic spices.",
    cookingTime: "5 hours",
    spicyLevel: "mild",
    calories: 320,
    allergens: ["Dairy"]
  },
  {
    id: 14,
    name: "Hyderabadi Biryani",
    category: "main",
    price: 449,
    imageUrl: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?q=80&w=400&h=300&auto=format",
    ingredients: ["Basmati rice", "Chicken", "Yogurt", "Saffron", "Fried onions"],
    dietaryTag: "non-veg",
    rating: 4.9,
    reviewCount: 115,
    description: "Fragrant basmati rice layered with tender chicken, yogurt marinade, and aromatic spices, slow-cooked in the dum style.",
    cookingTime: "55 min",
    spicyLevel: "medium",
    calories: 650,
    allergens: ["Dairy"]
  },
  {
    id: 15,
    name: "Chole Bhature",
    category: "main",
    price: 299,
    imageUrl: "https://images.unsplash.com/photo-1617692855027-33b14f061079?q=80&w=400&h=300&auto=format",
    ingredients: ["Chickpeas", "Flour", "Spices", "Onions", "Tomatoes"],
    dietaryTag: "veg",
    rating: 4.6,
    reviewCount: 82,
    description: "Spicy chickpea curry served with deep-fried leavened bread, garnished with onions and lemon wedges.",
    cookingTime: "45 min",
    spicyLevel: "hot",
    calories: 580,
    allergens: ["Gluten"]
  },
  {
    id: 16,
    name: "Fish Curry",
    category: "main",
    price: 379,
    imageUrl: "https://images.unsplash.com/photo-1626711934535-9749ea30dba8?q=80&w=400&h=300&auto=format",
    ingredients: ["Fish", "Coconut milk", "Tomatoes", "Tamarind", "Spices"],
    dietaryTag: "non-veg",
    rating: 4.7,
    reviewCount: 69,
    description: "Tender fish cooked in a tangy and spicy curry made with coconut milk, tomatoes, and tamarind.",
    cookingTime: "35 min",
    spicyLevel: "hot",
    calories: 410,
    allergens: ["Fish"]
  },
  {
    id: 17,
    name: "Malai Kofta",
    category: "main",
    price: 329,
    imageUrl: "https://images.unsplash.com/photo-1567420722114-08ba29bb7c1e?q=80&w=400&h=300&auto=format",
    ingredients: ["Paneer", "Potatoes", "Cashews", "Cream", "Tomatoes"],
    dietaryTag: "veg",
    rating: 4.8,
    reviewCount: 73,
    description: "Soft potato and cheese dumplings served in a rich, creamy tomato-based gravy with cashews and spices.",
    cookingTime: "50 min",
    spicyLevel: "mild",
    calories: 520,
    allergens: ["Dairy", "Nuts"]
  },
  {
    id: 18,
    name: "Rogan Josh",
    category: "main",
    price: 399,
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=400&h=300&auto=format",
    ingredients: ["Lamb", "Yogurt", "Kashmiri chilies", "Ginger", "Spices"],
    dietaryTag: "non-veg",
    rating: 4.8,
    reviewCount: 68,
    description: "Aromatic Kashmiri lamb curry cooked with yogurt, browned onions, and a blend of fragrant spices.",
    cookingTime: "60 min",
    spicyLevel: "medium",
    calories: 590,
    allergens: ["Dairy"]
  },
  {
    id: 19,
    name: "Vegetable Jalfrezi",
    category: "main",
    price: 299,
    imageUrl: "https://images.unsplash.com/photo-1565280654386-36c3ea205191?q=80&w=400&h=300&auto=format",
    ingredients: ["Mixed vegetables", "Bell peppers", "Tomatoes", "Onions", "Spices"],
    dietaryTag: "vegan",
    rating: 4.5,
    reviewCount: 58,
    description: "Colorful mixed vegetables stir-fried with bell peppers, onions, and tomatoes in a spicy tangy sauce.",
    cookingTime: "30 min",
    spicyLevel: "hot",
    calories: 280,
    allergens: []
  },
  {
    id: 20,
    name: "Prawn Coconut Curry",
    category: "main",
    price: 449,
    imageUrl: "https://images.unsplash.com/photo-1525184782196-8e2ded604bf7?q=80&w=400&h=300&auto=format",
    ingredients: ["Prawns", "Coconut milk", "Curry leaves", "Mustard seeds", "Red chilies"],
    dietaryTag: "non-veg",
    rating: 4.7,
    reviewCount: 61,
    description: "Succulent prawns cooked in a creamy coconut milk gravy with curry leaves and South Indian spices.",
    cookingTime: "35 min",
    spicyLevel: "medium",
    calories: 420,
    allergens: ["Shellfish"]
  },
  
  // Desserts
  {
    id: 21,
    name: "Gulab Jamun",
    category: "desserts",
    price: 159,
    imageUrl: "https://images.unsplash.com/photo-1601303516525-3241860781a0?q=80&w=400&h=300&auto=format",
    ingredients: ["Milk solids", "Flour", "Sugar syrup", "Cardamom", "Rose water"],
    dietaryTag: "veg",
    rating: 4.9,
    reviewCount: 98,
    description: "Soft, melt-in-your-mouth milk solid dumplings soaked in rose and cardamom flavored sugar syrup.",
    cookingTime: "40 min",
    spicyLevel: "mild",
    calories: 290,
    allergens: ["Dairy", "Gluten"]
  },
  {
    id: 22,
    name: "Rasmalai",
    category: "desserts",
    price: 199,
    imageUrl: "https://images.unsplash.com/photo-1620894169431-a2161678dd70?q=80&w=400&h=300&auto=format",
    ingredients: ["Cottage cheese", "Milk", "Saffron", "Pistachios", "Sugar"],
    dietaryTag: "veg",
    rating: 4.8,
    reviewCount: 86,
    description: "Soft cottage cheese patties soaked in creamy, cardamom-flavored milk, garnished with pistachios and saffron.",
    cookingTime: "50 min",
    spicyLevel: "mild",
    calories: 320,
    allergens: ["Dairy", "Nuts"]
  },
  {
    id: 23,
    name: "Gajar Ka Halwa",
    category: "desserts",
    price: 179,
    imageUrl: "https://images.unsplash.com/photo-1627834377411-8da5f4f09de8?q=80&w=400&h=300&auto=format",
    ingredients: ["Carrots", "Milk", "Sugar", "Ghee", "Nuts"],
    dietaryTag: "veg",
    rating: 4.7,
    reviewCount: 75,
    description: "Traditional carrot pudding made with grated carrots slow-cooked in milk, sugar, and ghee, garnished with nuts.",
    cookingTime: "60 min",
    spicyLevel: "mild",
    calories: 350,
    allergens: ["Dairy", "Nuts"]
  },
  {
    id: 24,
    name: "Phirni",
    category: "desserts",
    price: 169,
    imageUrl: "https://images.unsplash.com/photo-1616671285412-aa56866b3adf?q=80&w=400&h=300&auto=format",
    ingredients: ["Rice", "Milk", "Sugar", "Cardamom", "Pistachios"],
    dietaryTag: "veg",
    rating: 4.6,
    reviewCount: 62,
    description: "Creamy rice pudding made with ground rice, milk, and sugar, flavored with cardamom and garnished with pistachios.",
    cookingTime: "45 min",
    spicyLevel: "mild",
    calories: 280,
    allergens: ["Dairy", "Nuts"]
  },
  {
    id: 25,
    name: "Jalebi",
    category: "desserts",
    price: 129,
    imageUrl: "https://images.unsplash.com/photo-1589249125609-c683116370d1?q=80&w=400&h=300&auto=format",
    ingredients: ["Flour", "Yogurt", "Sugar syrup", "Saffron", "Cardamom"],
    dietaryTag: "veg",
    rating: 4.8,
    reviewCount: 91,
    description: "Crispy, pretzel-shaped deep-fried sweets soaked in saffron and cardamom flavored sugar syrup.",
    cookingTime: "30 min",
    spicyLevel: "mild",
    calories: 310,
    allergens: ["Gluten", "Dairy"]
  },
  {
    id: 26,
    name: "Kulfi",
    category: "desserts",
    price: 149,
    imageUrl: "https://images.unsplash.com/photo-1590308530012-7bdb0606f380?q=80&w=400&h=300&auto=format",
    ingredients: ["Milk", "Sugar", "Pistachios", "Almonds", "Cardamom"],
    dietaryTag: "veg",
    rating: 4.9,
    reviewCount: 88,
    description: "Traditional Indian frozen dessert made with reduced milk, sugar, and aromatic spices, garnished with nuts.",
    cookingTime: "4 hours",
    spicyLevel: "mild",
    calories: 250,
    allergens: ["Dairy", "Nuts"]
  },
  {
    id: 27,
    name: "Rasgulla",
    category: "desserts",
    price: 159,
    imageUrl: "https://images.unsplash.com/photo-1606479677987-1233acb888c2?q=80&w=400&h=300&auto=format",
    ingredients: ["Cottage cheese", "Sugar syrup", "Rose water", "Cardamom", "Saffron"],
    dietaryTag: "veg",
    rating: 4.7,
    reviewCount: 79,
    description: "Soft and spongy cheese balls soaked in light sugar syrup, flavored with rose water and cardamom.",
    cookingTime: "40 min",
    spicyLevel: "mild",
    calories: 220,
    allergens: ["Dairy"]
  },
  {
    id: 28,
    name: "Payasam",
    category: "desserts",
    price: 179,
    imageUrl: "https://images.unsplash.com/photo-1612633201753-b2275a288493?q=80&w=400&h=300&auto=format",
    ingredients: ["Rice", "Milk", "Sugar", "Cardamom", "Cashews"],
    dietaryTag: "veg",
    rating: 4.6,
    reviewCount: 68,
    description: "South Indian rice pudding cooked in milk and sugar, flavored with cardamom and garnished with fried cashews.",
    cookingTime: "50 min",
    spicyLevel: "mild",
    calories: 310,
    allergens: ["Dairy", "Nuts"]
  },
  {
    id: 29,
    name: "Mysore Pak",
    category: "desserts",
    price: 189,
    imageUrl: "https://images.unsplash.com/photo-1631452180775-4bbb5a1077f3?q=80&w=400&h=300&auto=format",
    ingredients: ["Gram flour", "Ghee", "Sugar", "Cardamom"],
    dietaryTag: "veg",
    rating: 4.7,
    reviewCount: 72,
    description: "Traditional South Indian sweet made from gram flour, ghee, and sugar, with a melt-in-mouth texture.",
    cookingTime: "30 min",
    spicyLevel: "mild",
    calories: 340,
    allergens: ["Dairy"]
  },
  {
    id: 30,
    name: "Shrikhand",
    category: "desserts",
    price: 169,
    imageUrl: "https://images.unsplash.com/photo-1579028029453-f98c8c6160f0?q=80&w=400&h=300&auto=format",
    ingredients: ["Hung curd", "Sugar", "Saffron", "Cardamom", "Pistachios"],
    dietaryTag: "veg",
    rating: 4.6,
    reviewCount: 65,
    description: "Creamy sweetened yogurt flavored with cardamom and saffron, garnished with pistachios.",
    cookingTime: "4 hours",
    spicyLevel: "mild",
    calories: 220,
    allergens: ["Dairy", "Nuts"]
  },
  
  // Sides
  {
    id: 31,
    name: "Butter Naan",
    category: "sides",
    price: 79,
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=400&h=300&auto=format",
    ingredients: ["All-purpose flour", "Yogurt", "Butter", "Garlic", "Coriander"],
    dietaryTag: "veg",
    rating: 4.9,
    reviewCount: 95,
    description: "Soft leavened flatbread cooked in a tandoor and brushed with butter.",
    cookingTime: "20 min",
    spicyLevel: "mild",
    calories: 250,
    allergens: ["Gluten", "Dairy"]
  },
  {
    id: 32,
    name: "Garlic Naan",
    category: "sides",
    price: 89,
    imageUrl: "https://images.unsplash.com/photo-1596797038530-2c107229654b?q=80&w=400&h=300&auto=format",
    ingredients: ["All-purpose flour", "Yogurt", "Garlic", "Butter", "Coriander"],
    dietaryTag: "veg",
    rating: 4.8,
    reviewCount: 88,
    description: "Soft leavened flatbread topped with minced garlic and fresh coriander, cooked in a tandoor.",
    cookingTime: "20 min",
    spicyLevel: "mild",
    calories: 260,
    allergens: ["Gluten", "Dairy"]
  },
  {
    id: 33,
    name: "Jeera Rice",
    category: "sides",
    price: 149,
    imageUrl: "https://images.unsplash.com/photo-1596450514735-111a2fc8c3fb?q=80&w=400&h=300&auto=format",
    ingredients: ["Basmati rice", "Cumin seeds", "Ghee", "Bay leaf", "Coriander"],
    dietaryTag: "veg",
    rating: 4.6,
    reviewCount: 72,
    description: "Fragrant basmati rice cooked with cumin seeds, ghee, and aromatic spices.",
    cookingTime: "25 min",
    spicyLevel: "mild",
    calories: 280,
    allergens: ["Dairy"]
  },
  {
    id: 34,
    name: "Raita",
    category: "sides",
    price: 99,
    imageUrl: "https://images.unsplash.com/photo-1626433262870-9fbea19ffbf6?q=80&w=400&h=300&auto=format",
    ingredients: ["Yogurt", "Cucumber", "Tomatoes", "Onions", "Cumin powder"],
    dietaryTag: "veg",
    rating: 4.5,
    reviewCount: 65,
    description: "Cool yogurt dip mixed with cucumber, tomatoes, onions, and mild spices.",
    cookingTime: "10 min",
    spicyLevel: "mild",
    calories: 120,
    allergens: ["Dairy"]
  },
  {
    id: 35,
    name: "Laccha Paratha",
    category: "sides",
    price: 69,
    imageUrl: "https://images.unsplash.com/photo-1619221882220-947b3d3c8861?q=80&w=400&h=300&auto=format",
    ingredients: ["Wheat flour", "Ghee", "Salt"],
    dietaryTag: "veg",
    rating: 4.7,
    reviewCount: 78,
    description: "Multi-layered flaky flatbread cooked on a griddle with ghee.",
    cookingTime: "25 min",
    spicyLevel: "mild",
    calories: 270,
    allergens: ["Gluten", "Dairy"]
  },
  {
    id: 36,
    name: "Papad",
    category: "sides",
    price: 49,
    imageUrl: "https://images.unsplash.com/photo-1605130284535-11dd9eedc58a?q=80&w=400&h=300&auto=format",
    ingredients: ["Lentil flour", "Black pepper", "Cumin seeds"],
    dietaryTag: "vegan",
    rating: 4.4,
    reviewCount: 62,
    description: "Thin, crispy lentil wafers roasted or fried, a perfect accompaniment to any Indian meal.",
    cookingTime: "5 min",
    spicyLevel: "mild",
    calories: 80,
    allergens: []
  },
  {
    id: 37,
    name: "Vegetable Pulao",
    category: "sides",
    price: 199,
    imageUrl: "https://images.unsplash.com/photo-1589648751789-e329b7a249ca?q=80&w=400&h=300&auto=format",
    ingredients: ["Basmati rice", "Mixed vegetables", "Whole spices", "Ghee", "Mint"],
    dietaryTag: "veg",
    rating: 4.6,
    reviewCount: 70,
    description: "Fragrant basmati rice cooked with mixed vegetables and whole spices.",
    cookingTime: "30 min",
    spicyLevel: "mild",
    calories: 310,
    allergens: ["Dairy"]
  },
  {
    id: 38,
    name: "Onion Salad",
    category: "sides",
    price: 79,
    imageUrl: "https://images.unsplash.com/photo-1623428453054-24172679f633?q=80&w=400&h=300&auto=format",
    ingredients: ["Red onions", "Green chilies", "Lemon juice", "Coriander", "Chaat masala"],
    dietaryTag: "vegan",
    rating: 4.3,
    reviewCount: 56,
    description: "Fresh red onions mixed with green chilies, lemon juice, and chaat masala.",
    cookingTime: "5 min",
    spicyLevel: "medium",
    calories: 60,
    allergens: []
  },
  {
    id: 39,
    name: "Masala Papad",
    category: "sides",
    price: 69,
    imageUrl: "https://images.unsplash.com/photo-1617692855027-33b14f061079?q=80&w=400&h=300&auto=format",
    ingredients: ["Papad", "Onions", "Tomatoes", "Chaat masala", "Coriander"],
    dietaryTag: "vegan",
    rating: 4.5,
    reviewCount: 64,
    description: "Crispy roasted papad topped with chopped onions, tomatoes, and tangy chaat masala.",
    cookingTime: "10 min",
    spicyLevel: "medium",
    calories: 90,
    allergens: []
  },
  {
    id: 40,
    name: "Green Salad",
    category: "sides",
    price: 89,
    imageUrl: "https://images.unsplash.com/photo-1547496502-affa22d38842?q=80&w=400&h=300&auto=format",
    ingredients: ["Cucumber", "Tomatoes", "Onions", "Carrots", "Lemon juice"],
    dietaryTag: "vegan",
    rating: 4.4,
    reviewCount: 58,
    description: "Fresh mix of sliced cucumber, tomatoes, onions, and carrots with a sprinkle of chaat masala.",
    cookingTime: "10 min",
    spicyLevel: "mild",
    calories: 70,
    allergens: []
  },
  
  // Beverages
  {
    id: 41,
    name: "Masala Chai",
    category: "beverages",
    price: 79,
    imageUrl: "https://images.unsplash.com/photo-1578853156036-b25dff7d023b?q=80&w=400&h=300&auto=format",
    ingredients: ["Black tea", "Milk", "Cardamom", "Ginger", "Cinnamon"],
    dietaryTag: "veg",
    rating: 4.8,
    reviewCount: 95,
    description: "Traditional Indian spiced tea brewed with aromatic spices, milk, and sugar.",
    cookingTime: "15 min",
    spicyLevel: "mild",
    calories: 120,
    allergens: ["Dairy"]
  },
  {
    id: 42,
    name: "Mango Lassi",
    category: "beverages",
    price: 129,
    imageUrl: "https://images.unsplash.com/photo-1605256266331-f9ed2da3d7e2?q=80&w=400&h=300&auto=format",
    ingredients: ["Yogurt", "Mango pulp", "Sugar", "Cardamom", "Ice"],
    dietaryTag: "veg",
    rating: 4.9,
    reviewCount: 88,
    description: "Refreshing yogurt drink blended with sweet mango pulp, sugar, and a hint of cardamom.",
    cookingTime: "10 min",
    spicyLevel: "mild",
    calories: 190,
    allergens: ["Dairy"]
  },
  {
    id: 43,
    name: "Sweet Lassi",
    category: "beverages",
    price: 99,
    imageUrl: "https://images.unsplash.com/photo-1553682544-4ccf2778c9a8?q=80&w=400&h=300&auto=format",
    ingredients: ["Yogurt", "Sugar", "Cardamom", "Rose water", "Ice"],
    dietaryTag: "veg",
    rating: 4.6,
    reviewCount: 72,
    description: "Creamy yogurt drink sweetened with sugar and flavored with cardamom and rose water.",
    cookingTime: "10 min",
    spicyLevel: "mild",
    calories: 170,
    allergens: ["Dairy"]
  },
  {
    id: 44,
    name: "Fresh Lime Soda",
    category: "beverages",
    price: 89,
    imageUrl: "https://images.unsplash.com/photo-1623381748580-887e92b29742?q=80&w=400&h=300&auto=format",
    ingredients: ["Lemon juice", "Soda water", "Sugar", "Salt", "Mint leaves"],
    dietaryTag: "vegan",
    rating: 4.5,
    reviewCount: 65,
    description: "Refreshing drink made with fresh lime juice and soda water, available in sweet, salty, or mixed flavors.",
    cookingTime: "5 min",
    spicyLevel: "mild",
    calories: 80,
    allergens: []
  },
  {
    id: 45,
    name: "Watermelon Juice",
    category: "beverages",
    price: 109,
    imageUrl: "https://images.unsplash.com/photo-1577493540830-f65a6c572412?q=80&w=400&h=300&auto=format",
    ingredients: ["Watermelon", "Mint leaves", "Lemon juice", "Ice", "Sugar"],
    dietaryTag: "vegan",
    rating: 4.7,
    reviewCount: 68,
    description: "Refreshing juice made from fresh watermelon, with a hint of mint and lemon.",
    cookingTime: "10 min",
    spicyLevel: "mild",
    calories: 110,
    allergens: []
  },
  {
    id: 46,
    name: "Buttermilk",
    category: "beverages",
    price: 79,
    imageUrl: "https://images.unsplash.com/photo-1526831582540-ef4be0233289?q=80&w=400&h=300&auto=format",
    ingredients: ["Yogurt", "Cumin powder", "Coriander", "Green chilies", "Ginger"],
    dietaryTag: "veg",
    rating: 4.5,
    reviewCount: 62,
    description: "Spiced yogurt-based drink with cumin, coriander, and green chilies, perfect for digestion.",
    cookingTime: "10 min",
    spicyLevel: "mild",
    calories: 90,
    allergens: ["Dairy"]
  },
  {
    id: 47,
    name: "Cold Coffee",
    category: "beverages",
    price: 139,
    imageUrl: "https://images.unsplash.com/photo-1580661869408-55ab0e60688b?q=80&w=400&h=300&auto=format",
    ingredients: ["Coffee", "Milk", "Sugar", "Ice cream", "Chocolate sauce"],
    dietaryTag: "veg",
    rating: 4.8,
    reviewCount: 76,
    description: "Creamy blended coffee drink topped with vanilla ice cream and chocolate sauce.",
    cookingTime: "15 min",
    spicyLevel: "mild",
    calories: 240,
    allergens: ["Dairy"]
  },
  {
    id: 48,
    name: "Rose Milk",
    category: "beverages",
    price: 99,
    imageUrl: "https://images.unsplash.com/photo-1626168578388-56f295665e12?q=80&w=400&h=300&auto=format",
    ingredients: ["Milk", "Rose syrup", "Sugar", "Ice", "Rose petals"],
    dietaryTag: "veg",
    rating: 4.6,
    reviewCount: 64,
    description: "Sweet and fragrant chilled milk flavored with rose syrup and garnished with rose petals.",
    cookingTime: "10 min",
    spicyLevel: "mild",
    calories: 170,
    allergens: ["Dairy"]
  },
  {
    id: 49,
    name: "Mint Mojito",
    category: "beverages",
    price: 129,
    imageUrl: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?q=80&w=400&h=300&auto=format",
    ingredients: ["Lime", "Mint leaves", "Sugar", "Soda water", "Ice"],
    dietaryTag: "vegan",
    rating: 4.7,
    reviewCount: 70,
    description: "Refreshing mocktail with muddled mint leaves, lime juice, sugar, and soda water.",
    cookingTime: "10 min",
    spicyLevel: "mild",
    calories: 100,
    allergens: []
  },
  {
    id: 50,
    name: "Badam Milk",
    category: "beverages",
    price: 119,
    imageUrl: "https://images.unsplash.com/photo-1626778672297-9320eff89767?q=80&w=400&h=300&auto=format",
    ingredients: ["Milk", "Almonds", "Saffron", "Cardamom", "Sugar"],
    dietaryTag: "veg",
    rating: 4.7,
    reviewCount: 68,
    description: "Nourishing milk drink made with almonds, saffron, and cardamom, served hot or cold.",
    cookingTime: "20 min",
    spicyLevel: "mild",
    calories: 210,
    allergens: ["Dairy", "Nuts"]
  }
];

export const orders: Order[] = [
  {
    id: 1001,
    tableNumber: 5,
    items: [
      { ...menuItems[2], quantity: 2 },
      { ...menuItems[7], quantity: 1 }
    ],
    orderType: "dine-in",
    status: "served",
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(), // 45 minutes ago
    total: 2 * menuItems[2].price + menuItems[7].price
  },
  {
    id: 1002,
    tableNumber: 3,
    items: [
      { ...menuItems[0], quantity: 1 },
      { ...menuItems[3], quantity: 1 },
      { ...menuItems[5], quantity: 2 }
    ],
    orderType: "dine-in", 
    status: "preparing",
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(), // 15 minutes ago
    total: menuItems[0].price + menuItems[3].price + 2 * menuItems[5].price
  },
  {
    id: 1003,
    tableNumber: 7,
    items: [
      { ...menuItems[1], quantity: 1 },
      { ...menuItems[6], quantity: 2 }
    ],
    orderType: "parcel",
    status: "pending",
    timestamp: new Date().toISOString(), // Just now
    total: menuItems[1].price + 2 * menuItems[6].price
  }
];

export const getRandomTableNumber = (): number => {
  return Math.floor(Math.random() * 20) + 1; // Random table between 1-20
};
